# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: alphadoc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 'Linux-Python 3.8', python: '3.8', os: ubuntu-latest}
          - {name: 'Linux-Python 3.7', python: '3.7', os: ubuntu-latest}
          - {name: 'Linux-Python 3.6', python: '3.6', os: ubuntu-latest}
          - {name: 'Mac-Python 3.8', python: '3.8', os: macos-latest}
          - {name: 'Mac-Python 3.7', python: '3.7', os: macos-latest}
          - {name: 'Mac-Python 3.6', python: '3.6', os: macos-latest}


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
